### ISSUE TITLE
getting  unable to resolve a value after 10000 tries.

### ISSUE THREAD

**Issue by arjunashetty** [Cornutum/tcases#245] opened 2022-10-13 12:53 UTC
Hi Team, 

I am getting following error for all the testcases when i run :  mvn tcases:api-test 

swagger doc : swagger-petstore-api

Error : 
`RequestCaseDef[12,Body.application-json.Items.Contains.Value.Properties.id.Type=null,POST,/user/createWithList,FAILURE],requestBody,value,unique item[2] of 13: Unable to resolve a value after 10000 tries. No request case created for this test.`

**Comment by kerrykimbrough** [comment] 2022-10-13 23:39
Please send a copy of the OpenAPI document I can use to reproduce this. Also send the name of the file and the command that you are running. Also, if you have changed the configuration of the tcases-maven-plugin, send a copy of the pom.xml that defines this configuration.

**Comment by arjunashetty** [comment] 2022-10-14 08:56
The swagger-petstore open api is kept in this location : 
<img width="268" alt="image" src="https://user-images.githubusercontent.com/46148141/195805441-69f2fa0f-3079-4e59-b8d2-2c70b5c30af1.png">

attached the openapi.json file, which is default open api spec from swagger(pet-store): 

command used : mvn tcases:api-test[](url)
[openapi.zip](https://github.com/Cornutum/tcases/files/9784242/openapi.zip)

**Comment by arjunashetty** [comment] 2022-10-17 06:07
@kerrykimbrough  can you please update

**Comment by kerrykimbrough** [comment] 2022-10-17 17:54
I am able to reproduce this symptom, and I am investigating the cause. 

This test case is a complicated situation where TFOA has some limitations. As described by the log message, this is a test case for a `POST /user/createWithList` request in which the body must contain an array of unique object items, one of which must have an `id: null` property (an invalid value expected to cause a FAILURE). The trouble arrises when TFOA tries to "resolve" these requirements into actual values.

The only info available for resolution is the definition generated by Tcases for this test case. It specifies that the array must contain multiple unique items and that one of them must  have `id: null`. But there is not enough information available to derive values for the other array items. It specifies that they must be `object` values, but the complete object model is not included. TFOA can only try random objects with random properties, which of course are very unlikely to match the OpenAPI definition of this request.

You will notice that the log shows several other instances of this kind of resolution failure. For some of them, it may be possible to extend the test case with more info for resolution. But for the specific case you reported, this approach won't work -- the info needed to describe an arbitrarily complex object value is just too unbounded.

**Comment by kerrykimbrough** [comment] 2022-10-18 16:17
I don't understand your last comment. My results show that many test cases were generated for each of the API requests defined in this OpenAPI definition, including tests for `POST /user/createWithList`. In fact, of the 142 test cases generated, only 22 were skipped because of a resolution failure.

Nevertheless, the 22 skipped tests are definitely an issue that I am investigating.

**Comment by kerrykimbrough** [comment] 2022-10-19 19:55
I've found an improvement that eliminates these resolution failures. Look for a new release soon.

**Comment by arjunashetty** [comment] 2022-10-21 09:18
Thank you @kerrykimbrough

**Comment by kerrykimbrough** [comment] 2022-10-21 18:18
Fixed by PR #246

**Closed by kerrykimbrough** 2022-10-21 18:18 UTC
