### ISSUE TITLE
getting command not found 

### ISSUE THREAD

**Issue by arjunashetty** [Cornutum/tcases#210] opened 2021-09-21 16:29 UTC
getting following error : 
arjun@Arjuns-MBP bin % tcases-api
Error: Could not find or load main class org.cornutum.tcases.openapi.ApiCommand

Operating sys : MAC OS

**Comment by kerrykimbrough** [comment] 2021-09-21 17:31
See discussion for issue #209

**Comment by arjunashetty** [comment] 2021-09-22 04:36
commented on  thread #209 , kindly check

**Comment by kerrykimbrough** [comment] 2021-09-23 16:28
Duplicate of #209

**Closed by kerrykimbrough** 2021-09-23 16:28 UTC
