### ISSUE TITLE
Running the petstore.yaml from Maven Plugin

### ISSUE THREAD

**Issue by mhettiarac** [Cornutum/tcases#124] opened 2020-06-26 18:02 UTC
HI I have created a maven new maven project and followed following steps:
 - Placed the petsore.yaml in the location "\src\test\tcases\openapi"
- Then ran the mvn tcases:api-test -Dproject=petstore command

Getting the following exception:
[ERROR] Failed to execute goal org.cornutum.tcases:tcases-maven-plugin:3.4.0:api-test (default-cli) on project TcasesSampleMaven: Can't generate requested tests: JUnitTestWriter[]: Can't write test for TestSour
ce[RequestTestDef[Swagger Petstore],[],[]]: Can't write test=SwaggerPetstore: No package defined for target=JavaTestTarget[package=<null>,dir=C:\Wiley Docs\API researchs\TcasesSampleMaven\target\generated-test-
sources\java] -> [Help 1]

Great help if you can advice why am I getting this error?

![maven-tcases](https://user-images.githubusercontent.com/51822287/85887334-31ea3000-b805-11ea-920b-56091808937f.png)

**Comment by kerrykimbrough** [comment] 2020-06-26 18:21
You need to define the Java package for the generated test class. There are 2 ways to do that. For example, let's suppose you want the package to be `org.myapp.mypackage`.

1. Put the OpenAPI spec in `src/test/tcases/openapi/org/myapp/mypackage` (recommended)
1. Define the package on the command line: `mvn tcases:api-test -DtestPackage=org.myapp.mypackage`

**Comment by mhettiarac** [comment] 2020-06-26 18:30
@kerrykimbrough Yes this time the program executed, But Im getting an empty file for SwaggerPetstoreTest.java
![EmptyJavaTests](https://user-images.githubusercontent.com/51822287/85889469-2ac52100-b809-11ea-82d0-3cdf0d8bb987.png)

**Comment by kerrykimbrough** [comment] 2020-06-26 18:38
Are you looking at the file listed in the "Writing API test to..." line?

**Comment by kerrykimbrough** [comment] 2020-06-26 18:40
You may have to refresh the view in your IDE.

**Comment by mhettiarac** [comment] 2020-06-26 18:49
Thanks for pointing me to the correct location,
But still I do not get the tests generated in the Java test class:

BTWI have executed the command : 
mvn tcases:api-test -DtestPackage=src.test.tcases.openapi.org.app.petstore.yaml

![maven-tcases-junit-tests](https://user-images.githubusercontent.com/51822287/85890864-d2435300-b80b-11ea-86d3-10959c3d54e6.png)

**Comment by kerrykimbrough** [comment] 2020-06-26 19:39
That's a very odd package name! But I'm sure you know that.

**Comment by kerrykimbrough** [comment] 2020-06-26 19:42
I can't explain why the test class body is empty. Based on what you've shown me, that makes no sense.

What is the Java JVM implementation that is used by your Maven installation? What does `mvn -v` show?

**Comment by mhettiarac** [comment] 2020-06-26 19:46
![image](https://user-images.githubusercontent.com/51822287/85895170-c65b8f00-b813-11ea-8148-c3d94f40ceb1.png)

**Comment by kerrykimbrough** [comment] 2020-06-27 00:41
I can now reproduce this problem, and I understand the cause. A fix is on the way soon!

**Comment by mhettiarac** [comment] 2020-06-27 14:20
Thank you so much for the quick response @kerrykimbrough .. Any ETA for the Fix ?

**Comment by kerrykimbrough** [comment] 2020-06-27 15:55
Look for a release 3.4.1 no later than 7/1

**Comment by kerrykimbrough** [comment] 2020-06-27 19:01
Fixed by PR #125

**Closed by kerrykimbrough** 2020-06-27 19:01 UTC

**Comment by mhettiarac** [comment] 2020-06-28 14:04
I see the 3.4.1 is not yet availble.. @kerrykimbrough  Thanks much for the fix, please let us know once the jars are released..

**Comment by kerrykimbrough** [comment] 2020-06-28 22:34
Fix now available in release 3.4.1

**Comment by mhettiarac** [comment] 2020-06-29 17:17
I just tried to download the  version 3.4.1, seems like its not yet available on the maven central repo? @kerrykimbrough

**Comment by mhettiarac** [comment] 2020-06-30 03:49
It got available today morning and now the issue is resolved.. Thanks much for the support @kerrykimbrough
