### ISSUE TITLE
OpenAPI: `multipleOf` in spec file - *RequestsTest (Junit/TestNG) are not generated 

### ISSUE THREAD

**Issue by sundarlogan** [Cornutum/tcases#285] opened 2023-12-28 02:01 UTC
Tcases Version: 4.0.2
OpenAPI Version: 3.0.0
OpenAPI Spec File: Attached 
[petstore-multipleOf.json](https://github.com/Cornutum/tcases/files/13782635/petstore-multipleOf.json)

Tried to generate Junit / TestNG API tests directly from the OpenAPI spec file using the 
Tcases cli cmd `tcases-api-test -t=testng -p=test.petstore.testng ./Documents/petstore-multipleof.json` and 
also via maven goal `mvn tcases:api-test`. It keeps loading - test not generated.
If we remove/comment `multipleOf` in OpenAPI spec file *RequestsTest (Junit/TestNG) are generated.

**Comment by kerrykimbrough** [comment] 2024-01-17 17:34
This problem is caused by a defect in the algorithm for creating a failure case using a `petPrice` value that is __not__ a multiple of 0.01. Look for a fix soon.

Meanwhile, you can work around the problem with a change to the schema for `petPrice`: define a `maximum` or `minimum` value with more than 2 fractional digits. For example: `"maximum": 0.123`.

**Comment by sundarlogan** [comment] 2024-01-18 16:43
Thank you @kerrykimbrough will try & use this work around..

**Comment by kerrykimbrough** [comment] 2024-01-19 19:09
Fixed in version 4.0.3

**Closed by kerrykimbrough** 2024-01-19 19:09 UTC

**Comment by kerrykimbrough** [comment] 2024-02-13 20:01
> But, when we add minimum & maximum values with multipleOf - facing issue (It keeps loading - test not generated) 

I can't reproduce this problem. Which version of Tcases are you using?

**Comment by kerrykimbrough** [comment] 2024-02-14 19:37
Here's the problem. When a numeric schema specifies both `minimum` and `maximum` (i.e. a bounded range), Tcases calculates the number of possible multiples within the range. (This is for the purpose of checking consistency with other schema constraints.) But in your example, because the `maximum` is so large, the number of possible multiples is enormous. Tcases isn't stuck -- it's just taking a really, really, really long time to count up all the multiples.

For now, you can work around the problem by using a smaller `maximum`. Meanwhile, I'm investigating a change to speed up the counting.

**Comment by kerrykimbrough** [comment] 2024-02-14 22:45
Fixed in release 4.0.5
